In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('output_test', sep = '<eol>')
df

/home/rishi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

,1,2,3
0,the bed is too big for a bed to be stacked on,beds don't have any place to do shopping,bed is
1,a soldier cannot run through water.,the thief will not work while a drop of tv.,a person does not use a
2,the airplane does not belong in the oven,not cooking things are used to process an ear.,if frying his dishes is
3,sugar is sweet and used to taste sugar,sugar is used specifically to make bread.,sugar is used to enhance liquids.
4,planes don't go in schools,"planes are usually closed at airports, not on...",planes are not usually in travelling.
...,...,...,...
995,to buy skin will make it burn even hotter,"after being closed typically is depressing, s...",there is no
996,"melting is a process of paper, it's not smart ...",ice cannot go in guns,ice cannot go
997,ice towels are not sold in roast light,you do not put water in a roast day.,in roast beef you would
998,there are no sand in sand unless it is made of...,sand is not something to eat,sand is an inanimate
999,it takes one to run around once.,a person can not run in space.,one cannot run in a vacuum for walking.

In [29]:
tf = pd.read_csv('temp', sep = ',')
tf

       id                                          FalseSent
0    1175        He loves to stroll at the park with his bed
1     452      The inverter was able to power the continent.
2     275            The chef put extra lemons on the pizza.
3     869                  sugar is used to make coffee sour
4      50  There are beautiful planes here and there in t...
..    ...                                                ...
995  1114           If it is a sunny day, you would got wet.
996     8              ice hockey is a financial institution
997  1945  He put water without a container in the freeze...
998  1053            The desert has sand that you can drink.
999  1123             My friend runs for 2 inches every day.

[1000 rows x 2 columns]

In [30]:
df['id'] = tf['id']
df

,1,2,3,id
0,the bed is too big for a bed to be stacked on,beds don't have any place to do shopping,bed is,1175
1,a soldier cannot run through water.,the thief will not work while a drop of tv.,a person does not use a,452
2,the airplane does not belong in the oven,not cooking things are used to process an ear.,if frying his dishes is,275
3,sugar is sweet and used to taste sugar,sugar is used specifically to make bread.,sugar is used to enhance liquids.,869
4,planes don't go in schools,"planes are usually closed at airports, not on...",planes are not usually in travelling.,50
...,...,...,...,...
995,to buy skin will make it burn even hotter,"after being closed typically is depressing, s...",there is no,1114
996,"melting is a process of paper, it's not smart ...",ice cannot go in guns,ice cannot go,8
997,ice towels are not sold in roast light,you do not put water in a roast day.,in roast beef you would,1945
998,there are no sand in sand unless it is made of...,sand is not something to eat,sand is an inanimate,1053
999,it takes one to run around once.,a person can not run in space.,one cannot run in a vacuum for walking.,1123

In [31]:
df = df[['id','1', '2', '3']]
df

,id,1,2,3
0,1175,the bed is too big for a bed to be stacked on,beds don't have any place to do shopping,bed is
1,452,a soldier cannot run through water.,the thief will not work while a drop of tv.,a person does not use a
2,275,the airplane does not belong in the oven,not cooking things are used to process an ear.,if frying his dishes is
3,869,sugar is sweet and used to taste sugar,sugar is used specifically to make bread.,sugar is used to enhance liquids.
4,50,planes don't go in schools,"planes are usually closed at airports, not on...",planes are not usually in travelling.
...,...,...,...,...
995,1114,to buy skin will make it burn even hotter,"after being closed typically is depressing, s...",there is no
996,8,"melting is a process of paper, it's not smart ...",ice cannot go in guns,ice cannot go
997,1945,ice towels are not sold in roast light,you do not put water in a roast day.,in roast beef you would
998,1053,there are no sand in sand unless it is made of...,sand is not something to eat,sand is an inanimate
999,1123,it takes one to run around once.,a person can not run in space.,one cannot run in a vacuum for walking.

In [21]:
df.to_csv('subtaskC_answers.csv', header = False, index = False)

In [32]:
def func(r):
    return str(r['1'])+'<eol>'+str(r['2'])+'<eol>'+str(r['3'])

fd = pd.DataFrame()
fd['id'] = df['id']
fd['lab'] = df.apply(lambda r:func(r), axis = 1)

fd

       id                                                lab
0    1175  the bed is too big for a bed to be stacked on ...
1     452  a soldier cannot run through water. <eol> the ...
2     275  the airplane does not belong in the oven <eol>...
3     869  sugar is sweet and used to taste sugar <eol> s...
4      50  planes don't go in schools <eol> planes are us...
..    ...                                                ...
995  1114  to buy skin will make it burn even hotter <eol...
996     8  melting is a process of paper, it's not smart ...
997  1945  ice towels are not sold in roast light <eol> y...
998  1053  there are no sand in sand unless it is made of...
999  1123  it takes one to run around once. <eol> a perso...

[1000 rows x 2 columns]

In [40]:
fd.to_csv('subtaskC_answers.csv', header = False, index = False)

In [39]:
!zip -r subtaskC_answers.csv submission.zip

	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (subtaskC_answers.csv)